services:
  backend:
    env_file:
      - .env
    container_name: cooktogether_api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000"
    volumes:
      - static-files:/app/staticfiles
    networks:
      - main

  nginx:
    container_name: nginx_cooktogether
    restart: always
    image: nginx:1.27.2-alpine
    volumes:
      - static-files:/app/staticfiles
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main

  certbot:
    container_name: certbot
    image: certbot/certbot:v2.11.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while true; do certbot renew; sleep 12h; done;'"

volumes:
  static-files:

networks:
  main: