name: Deploy to VM and Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VM
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via ssh
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }}
          REMOTE_USER: ${{ secrets.VM_USERNAME }}
          REMOTE_PORT: ${{ secrets.VM_SSH_PORT }}
          TARGET: "${{ secrets.VM_REMOTE_TARGET_FOLDER }}"
          EXCLUDE: ".git/"
          SCRIPT_AFTER: |
            cd ${{ secrets.VM_REMOTE_TARGET_FOLDER }}
            docker compose down
            docker compose up --build --force-recreate -d
            docker image prune -f
          SCRIPT_AFTER_REQUIRED: true
